# Generated by Django 5.1.3 on 2024-11-18 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminStaff',
        ),
        migrations.DeleteModel(
            name='AdmissionStaff',
        ),
        migrations.DeleteModel(
            name='GuidanceStaff',
        ),
        migrations.DeleteModel(
            name='RegistrarStaff',
        ),
    ]
