# Generated by Django 5.1.3 on 2024-11-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0003_registrarstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrarstaff',
            name='prefix',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
