# Generated by Django 5.1.3 on 2024-11-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0005_subject_facultystaff_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subjectname',
            field=models.CharField(max_length=30),
        ),
    ]
