# Generated by Django 5.1.3 on 2024-11-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0011_studentprofile_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='grades',
            field=models.ManyToManyField(blank=True, to='admin_staff.subject'),
        ),
    ]
