# Generated by Django 5.1.3 on 2024-11-26 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0012_alter_studentprofile_grades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='grades',
        ),
    ]
