# Generated by Django 5.1.3 on 2024-11-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0014_grades_remove_subject_average_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grades',
            field=models.ManyToManyField(blank=True, to='admin_staff.grades'),
        ),
    ]
