# Generated by Django 5.1.3 on 2024-11-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0015_subject_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='subject',
            field=models.ManyToManyField(blank=True, to='admin_staff.subject'),
        ),
    ]
