# Generated by Django 5.1.3 on 2024-11-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0016_studentprofile_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='grades',
        ),
        migrations.AddField(
            model_name='subject',
            name='average',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_grade_firstQ',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_grade_fourthQ',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_grade_secondQ',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_grade_thirdQ',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='grades',
        ),
    ]
