# Generated by Django 5.1.3 on 2024-11-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0017_remove_subject_grades_subject_average_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultystaff',
            name='subject',
        ),
        migrations.AddField(
            model_name='facultystaff',
            name='subject',
            field=models.ManyToManyField(blank=True, to='admin_staff.subject'),
        ),
    ]
