# Generated by Django 5.1.3 on 2024-11-26 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0019_grades_remove_subject_average_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultystaff',
            name='grades',
        ),
        migrations.DeleteModel(
            name='grades',
        ),
    ]
