# Generated by Django 5.1.3 on 2024-11-26 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0020_remove_facultystaff_grades_delete_grades'),
    ]

    operations = [
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_grade_firstQ', models.IntegerField(blank=True, null=True)),
                ('subject_grade_secondQ', models.IntegerField(blank=True, null=True)),
                ('subject_grade_thirdQ', models.IntegerField(blank=True, null=True)),
                ('subject_grade_fourthQ', models.IntegerField(blank=True, null=True)),
                ('average', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='facultystaff',
            name='grades',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_staff.grade'),
        ),
    ]
