# Generated by Django 5.1.3 on 2024-11-26 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0022_grade_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultystaff',
            name='grades',
        ),
    ]
