# Generated by Django 5.1.3 on 2024-11-26 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0023_remove_facultystaff_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='grades',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_staff.grade'),
        ),
    ]
