# Generated by Django 5.1.3 on 2024-11-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0025_grade_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='facultystaff',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='subject',
        ),
        migrations.DeleteModel(
            name='grade',
        ),
        migrations.DeleteModel(
            name='subject',
        ),
    ]
