# Generated by Django 4.2.17 on 2025-02-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0026_remove_studentprofile_grades_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_lrn', models.CharField(max_length=20)),
                ('subject_code', models.CharField(max_length=10)),
                ('first_grading', models.FloatField(blank=True, null=True)),
                ('second_grading', models.FloatField(blank=True, null=True)),
                ('third_grading', models.FloatField(blank=True, null=True)),
                ('fourth_grading', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
