# Generated by Django 4.2.17 on 2025-03-09 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0026_remove_studentprofile_grades_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_lrn', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=50)),
                ('first_grading', models.FloatField(blank=True, null=True)),
                ('second_grading', models.FloatField(blank=True, null=True)),
                ('third_grading', models.FloatField(blank=True, null=True)),
                ('fourth_grading', models.FloatField(blank=True, null=True)),
                ('final_grade', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('student_lrn', models.ForeignKey(db_column='student_lrn', on_delete=django.db.models.deletion.CASCADE, to='admin_staff.studentprofile')),
            ],
            options={
                'db_table': 'student_attendance',
                'managed': True,
            },
        ),
    ]
