# Generated by Django 4.2.17 on 2025-02-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0027_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_lrn', models.CharField(max_length=20, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('first_grading', models.FloatField(blank=True, null=True)),
                ('second_grading', models.FloatField(blank=True, null=True)),
                ('third_grading', models.FloatField(blank=True, null=True)),
                ('fourth_grading', models.FloatField(blank=True, null=True)),
                ('final_grade', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
