# Generated by Django 4.2.17 on 2025-03-20 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0028_studentprofile_ethnic_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accademicyear',
            name='accademicYear',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2001), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
