# Generated by Django 4.2.17 on 2025-02-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0028_studentgrade_delete_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='student_lrn',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
