# Generated by Django 4.2.17 on 2025-02-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0029_alter_studentgrade_student_lrn_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentgrade',
            table='admin_staff_studentgrade',
        ),
    ]
