# Generated by Django 4.2.17 on 2025-02-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0030_alter_studentgrade_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentgrade',
            table=None,
        ),
    ]
