# Generated by Django 4.2.17 on 2025-03-21 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0030_remove_accademicyear_accademicyear_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='level',
            new_name='grade',
        ),
        migrations.RemoveField(
            model_name='section',
            name='level',
        ),
        migrations.AddField(
            model_name='level',
            name='section_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_staff.section'),
        ),
    ]
