# Generated by Django 4.2.17 on 2025-02-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0031_alter_studentgrade_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accademicyear',
            name='accademicYear',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
