# Generated by Django 4.2.17 on 2025-03-23 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0032_remove_level_section_name_level_section_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='civil_status',
        ),
    ]
