# Generated by Django 4.2.17 on 2025-03-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0033_remove_studentprofile_civil_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_age',
            field=models.IntegerField(max_length=24, null=True),
        ),
    ]
