# Generated by Django 4.2.17 on 2025-02-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0033_studentattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='student_id',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='student_lrn',
            field=models.CharField(default='0000000000', max_length=20, unique=True),
        ),
    ]
