# Generated by Django 4.2.17 on 2025-03-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0034_studentprofile_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_age',
            field=models.IntegerField(null=True),
        ),
    ]
