# Generated by Django 4.2.17 on 2025-02-27 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0034_remove_studentattendance_student_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentattendance',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='student_lrn',
            field=models.ForeignKey(db_column='student_lrn', on_delete=django.db.models.deletion.CASCADE, to='admin_staff.studentprofile'),
        ),
        migrations.AlterModelTable(
            name='studentattendance',
            table='student_attendance',
        ),
    ]
