# Generated by Django 4.2.17 on 2025-03-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0035_alter_studentprofile_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='section_name',
            field=models.ManyToManyField(to='admin_staff.section'),
        ),
    ]
