# Generated by Django 4.2.17 on 2025-04-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0036_alter_level_section_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_age',
        ),
    ]
