# Generated by Django 4.2.17 on 2025-04-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0038_alter_studentprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='email',
        ),
    ]
