# Generated by Django 4.2.17 on 2025-04-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0039_remove_studentprofile_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_lrn',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
