# Generated by Django 4.2.17 on 2025-04-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0041_remove_studentprofile_ethnic_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='birth_place',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='religion',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
