# Generated by Django 4.2.17 on 2025-04-02 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0042_alter_studentprofile_birth_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='adviser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_staff.facultystaff'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_staff.level'),
        ),
    ]
