# Generated by Django 4.2.17 on 2025-04-02 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0044_studentprofile_age_studentprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='have_card',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='have_goodmoral',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='have_psa',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='adviser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_staff.facultystaff'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_staff.level'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_staff.section'),
        ),
    ]
