# Generated by Django 4.2.17 on 2025-04-02 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0045_studentprofile_have_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='contact_number',
        ),
    ]
