# Generated by Django 4.2.17 on 2025-04-02 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0047_studentprofile_guardian_or_parent_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='have_card',
        ),
    ]
