# Generated by Django 4.2.17 on 2025-04-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0048_remove_studentprofile_have_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='have_Form_137',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='have_Form_138',
            field=models.BooleanField(null=True),
        ),
    ]
