# Generated by Django 4.2.17 on 2025-04-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0049_studentprofile_have_form_137_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='guardian_last_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='guardian_middle_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='relationship',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='Guardian_Full_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
