# Generated by Django 4.2.17 on 2025-04-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0050_remove_studentprofile_guardian_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='have_goodmoral',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='have_psa',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='barangay',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='city',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='house_number',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='province',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='streets',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
