# Generated by Django 4.2.17 on 2025-04-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0051_remove_studentprofile_have_goodmoral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='have_Good_Moral_Certificate',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='have_PSA',
            field=models.BooleanField(null=True),
        ),
    ]
