# Generated by Django 4.2.17 on 2025-04-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0052_studentprofile_have_good_moral_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='have_Form_137',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='have_Form_138',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='have_Good_Moral_Certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='have_PSA',
            field=models.BooleanField(default=False),
        ),
    ]
