# Generated by Django 4.2.17 on 2025-04-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0053_alter_studentprofile_have_form_137_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='is_guardian',
            field=models.BooleanField(default=True),
        ),
    ]
