# Generated by Django 4.2.17 on 2025-04-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0055_alter_studentprofile_is_guardian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='Guardian_Full_Name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='ethnic_group',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='fathers_last_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='fathers_middle_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='fathers_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='guardian_or_parent_mobile_number',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='have_Form_137',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='have_Form_138',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='have_Good_Moral_Certificate',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='have_PSA',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='is_guardian',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mother_tongue',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mothers_last_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mothers_middle_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mothers_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='religion',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='birth_place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
