# Generated by Django 4.2.17 on 2025-04-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0056_remove_studentprofile_guardian_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='ethnic_group',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='religion',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
