# Generated by Django 4.2.17 on 2025-04-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0058_studentprofile_fathers_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_guardian',
            field=models.BooleanField(default=False),
        ),
    ]
