# Generated by Django 4.2.17 on 2025-04-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0059_studentprofile_is_guardian'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='Guardian_Full_Name',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_or_parent_mobile_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
