# Generated by Django 4.2.17 on 2025-04-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0060_studentprofile_guardian_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='have_Form_137',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='have_Form_138',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='have_Good_Moral_Certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='have_PSA',
            field=models.BooleanField(default=False),
        ),
    ]
