# Generated by Django 4.2.17 on 2025-04-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0061_studentprofile_have_form_137_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='Accelerated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='Balik_Aral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='CCT_Recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='Dropped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='Late_Enrolee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='Learner_with_Disability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='Transfer_In',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='Transfer_Out',
            field=models.BooleanField(default=False),
        ),
    ]
