# Generated by Django 4.2.17 on 2025-04-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0065_alter_studentprofile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='birth_place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='ethnic_group',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='mother_tongue',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='religion',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
