# Generated by Django 4.2.17 on 2025-04-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0066_alter_studentprofile_birth_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='fathers_last_name',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='fathers_middle_name',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='fathers_name',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='mothers_last_name',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='mothers_middle_name',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='mothers_name',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
