# Generated by Django 4.2.17 on 2025-04-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0067_alter_studentprofile_fathers_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='have_Form_138',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
