# Generated by Django 4.2.17 on 2025-04-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0069_alter_studentprofile_have_form_138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_or_parent_mobile_number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
