# Generated by Django 4.2.17 on 2025-04-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0071_studentprofile_choice_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='choice_field',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.BooleanField(choices=[('Male', 'Male'), ('Female', 'Female')]),
        ),
    ]
