# Generated by Django 4.2.17 on 2025-04-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0073_alter_studentprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.BooleanField(choices=[('Male', 'Male'), ('Female', 'Female')], default=False),
        ),
    ]
