# Generated by Django 4.2.17 on 2025-04-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0075_alter_studentprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='Accelerated',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='Balik_Aral',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='CCT_Recipient',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='Dropped',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='Late_Enrolee',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='Learner_with_Disability',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='Transfer_In',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='Transfer_Out',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('dropped', 'Dropped'), ('late_enrolee', 'Late Enrolee'), ('cct_recipient', 'CCT Recipient'), ('balik_aral', 'Balik Aral'), ('learner_with_disability', 'Learner with Disability'), ('accelerated', 'Accelerated')], default='transfer_out', max_length=100),
        ),
    ]
