# Generated by Django 4.2.17 on 2025-04-08 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0076_remove_studentprofile_accelerated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='age',
        ),
    ]
