# Generated by Django 4.2.17 on 2025-04-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0079_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Credit/Debit Card Payment', 'Credit/Debit Card Payment'), ('Bank Transfer', 'Bank Transfer'), ('Mobile Payment Apps', 'Mobile Payment Apps'), ('Office Transaction', 'Office Transaction')], default='Status', max_length=50, null=True),
        ),
    ]
