# Generated by Django 4.2.17 on 2025-04-26 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0082_remove_level_section_name_section_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultystaff',
            name='section',
        ),
        migrations.AddField(
            model_name='section',
            name='adviser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_staff.facultystaff'),
        ),
    ]
